# Generated by Django 5.0.6 on 2025-07-05 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField(db_column='reported_date')),
                ('my_otb', models.FloatField()),
                ('market_demand', models.FloatField()),
                ('furama_resort', models.FloatField(db_column='Furama Resort Danang')),
                ('hyatt_regency', models.FloatField(db_column='Hyatt Regency Danang Resort and Spa')),
                ('pullman_beach', models.FloatField(db_column='Pullman Danang Beach Resort')),
                ('sheraton_grand', models.FloatField(db_column='Sheraton Grand Danang Resort & Convention Center')),
                ('danang_marriott', models.FloatField(db_column='Danang Marriott Resort & Spa')),
                ('fusion_resort', models.FloatField(db_column='Fusion Resort and Villas Da Nang')),
                ('shilla_monogram', models.FloatField(db_column='Shilla Monogram Quangnam Danang')),
                ('koi_resort', models.FloatField(db_column='KOI Resort & Residence Da Nang')),
                ('marriott_non_nuoc', models.FloatField(db_column='Danang Marriott Resort & Spa, Non Nuoc Beach Villas')),
                ('premier_village', models.FloatField(db_column='Premier Village Danang Resort Managed By Accor')),
                ('furama_villas', models.FloatField(db_column='Furama Villas Danang')),
                ('updated_date', models.DateField(db_column='updated_date')),
            ],
            options={
                'db_table': 'daily_rates',
            },
        ),
        migrations.CreateModel(
            name='OtaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ota_reviews',
            },
        ),
        migrations.CreateModel(
            name='OtaReviewCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ota_review_criterion',
            },
        ),
        migrations.CreateModel(
            name='OtaReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.otareviewcriterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app.otareview')),
            ],
            options={
                'db_table': 'ota_review_score',
            },
        ),
    ]
